-- 00000000000017_market_briefs.sql
-- Daily market brief — one Korean-language summary covering the whole
-- watchlist (not per-stock; ai_commentary is per-stock). Shown on
-- /dashboard above the global cards.
--
-- Generated by cognition/market_brief.py from the same payload the
-- preview email uses (global_market + sector temps + top movers + risk
-- watch). Same forbidden-words guard as report.py.

CREATE TABLE IF NOT EXISTS market_briefs (
    date           DATE PRIMARY KEY,
    headline       VARCHAR(200) NOT NULL,
    body           TEXT NOT NULL,
    sector_view    TEXT,                                  -- 섹터별 흐름 한 단락
    top_picks      TEXT[],                                -- 강한 관심 top 종목 코멘트 3-5개
    risk_watch     TEXT[],                                -- 위험 신호 종목 / 매크로 코멘트 2-3개
    macro_summary  TEXT,                                  -- USDKRW, 10Y UST, VIX 한 단락
    model          VARCHAR(50) NOT NULL,
    cost_estimate  DOUBLE PRECISION,
    created_at     TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE market_briefs ENABLE ROW LEVEL SECURITY;
CREATE POLICY auth_read_market_briefs ON market_briefs FOR SELECT
    TO authenticated USING (TRUE);

NOTIFY pgrst, 'reload schema';
